spring:
  # 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/course?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml


# 日志打印级别
logging:
  level:
    com:
      course:
        server:
          mapper:
            debug
