spring:
  application:
    name: system

  # 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/course?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml

server:
  port: 9001
  servlet:
    context-path: /system

eureka:
  client:
    service-url:
      defautZone: http://localhost:8761/eureka/

# 日志打印级别
logging:
  level:
    com:
      course:
        system:
          mapper:
            debug
